// packages/angular/src/ccais-chatbot.component.ts
import "@ccais/embedded-chatbot-core";
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import type { ChatbotPosition } from "@ccais/embedded-chatbot-core";

@Component({
  selector: "ccais-chatbot-wrapper",
  template: `
    <ccais-chatbot
      [attr.chatbot-id]="chatbotId"
      [attr.name]="name"
      [attr.primary-color]="primaryColor"
      [attr.accent-color]="accentColor"
      [attr.position]="position"
      [attr.welcome-message]="welcomeMessage"
      [attr.placeholder]="placeholder"
      [attr.api-base-url]="apiBaseUrl"
    ></ccais-chatbot>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class CcaisChatbotComponent {
  @Input() chatbotId?: string;
  @Input() name?: string;
  @Input() primaryColor?: string;
  @Input() accentColor?: string;
  @Input() position?: ChatbotPosition;
  @Input() welcomeMessage?: string;
  @Input() placeholder?: string;
  @Input() apiBaseUrl?: string;
}

// packages/react/src/CcaisChatbot.tsx
import "@ccais/embedded-chatbot-core";
import type React from "react";
import type { ChatbotPosition } from "@ccais/embedded-chatbot-core";

export type CcaisChatbotProps = {
  chatbotId?: string;
  name?: string;
  primaryColor?: string;
  accentColor?: string;
  position?: ChatbotPosition;
  welcomeMessage?: string;
  placeholder?: string;
  apiBaseUrl?: string;
};

type CcaisChatbotElementAttributes = React.DetailedHTMLProps<
  React.HTMLAttributes<HTMLElement>,
  HTMLElement
> & {
  "chatbot-id"?: string;
  name?: string;
  "primary-color"?: string;
  "accent-color"?: string;
  position?: ChatbotPosition;
  "welcome-message"?: string;
  placeholder?: string;
  "api-base-url"?: string;
};

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "ccais-chatbot": CcaisChatbotElementAttributes;
    }
  }
}

export function CcaisChatbot({
  chatbotId,
  name,
  primaryColor,
  accentColor,
  position,
  welcomeMessage,
  placeholder,
  apiBaseUrl
}: CcaisChatbotProps) {
  return (
    <ccais-chatbot
      chatbot-id={chatbotId}
      name={name}
      primary-color={primaryColor}
      accent-color={accentColor}
      position={position}
      welcome-message={welcomeMessage}
      placeholder={placeholder}
      api-base-url={apiBaseUrl}
    />
  );
}
